# Generated by Django 5.2.14 on 2026-06-02 09:22

import config.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('area_name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['area_name'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('floor_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
            ],
            options={
                'ordering': ['section__section_name', 'floor_name'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='Hostel Management', max_length=150)),
                ('billing_calculation_method', models.CharField(choices=[('inclusive', 'Inclusive'), ('exclusive_start', 'Exclusive Start')], default='inclusive', max_length=30)),
                ('payment_window_start_day', models.PositiveSmallIntegerField(default=1)),
                ('payment_window_end_day', models.PositiveSmallIntegerField(default=5)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buildings', to='hostel.area')),
            ],
            options={
                'ordering': ['area__area_name', 'building_name'],
            },
        ),
        migrations.CreateModel(
            name='ExcelUploadLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_file', models.FileField(upload_to='excel_uploads/', validators=[config.validators.validate_excel_file])),
                ('total_rows', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failure_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], default='success', max_length=10)),
                ('log_details', models.JSONField(blank=True, default=list)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excel_upload_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('room_number', models.CharField(max_length=50)),
                ('room_name', models.CharField(blank=True, max_length=150)),
                ('room_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rooms', to='hostel.floor')),
            ],
            options={
                'ordering': ['floor__floor_name', 'room_number'],
            },
        ),
        migrations.CreateModel(
            name='Cot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cot_number', models.CharField(max_length=50)),
                ('cot_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('security_deposit', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Pending'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('blocked', 'Blocked')], default='available', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cots', to='hostel.room')),
            ],
            options={
                'ordering': ['room__room_number', 'cot_number'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='hostel.building')),
            ],
            options={
                'ordering': ['building__building_name', 'section_name'],
            },
        ),
        migrations.AddField(
            model_name='floor',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='floors', to='hostel.section'),
        ),
        migrations.AddConstraint(
            model_name='building',
            constraint=models.UniqueConstraint(fields=('area', 'building_name'), name='unique_building_per_area'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('floor', 'room_number'), name='unique_room_per_floor'),
        ),
        migrations.AddConstraint(
            model_name='cot',
            constraint=models.UniqueConstraint(fields=('room', 'cot_number'), name='unique_cot_per_room'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('building', 'section_name'), name='unique_section_per_building'),
        ),
        migrations.AddConstraint(
            model_name='floor',
            constraint=models.UniqueConstraint(fields=('section', 'floor_name'), name='unique_floor_per_section'),
        ),
    ]
