# Generated by Django 5.2.14 on 2026-06-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsetting',
            name='admin_contact_label',
            field=models.CharField(blank=True, default='Need Help?', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='admin_contact_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
