# Generated by Django 5.2.14 on 2026-06-04 11:35

import config.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostel", "0002_systemsetting_admin_contact_label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="area",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/areas/", validators=[config.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name="building",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/buildings/", validators=[config.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name="cot",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/cots/", validators=[config.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name="floor",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/floors/", validators=[config.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name="room",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/rooms/", validators=[config.validators.validate_image_file]),
        ),
        migrations.AddField(
            model_name="section",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="hostel_setup/sections/", validators=[config.validators.validate_image_file]),
        ),
    ]
