# Generated by Django 5.2.14 on 2026-06-02 09:22

import config.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_key', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['template_key'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('green_api', 'Green API'), ('whatsapp_cloud_api', 'WhatsApp Cloud API'), ('manual_placeholder', 'Manual Placeholder')], default='manual_placeholder', max_length=30)),
                ('instance_id', models.CharField(blank=True, max_length=150)),
                ('api_token', models.CharField(blank=True, max_length=255)),
                ('phone_number_id', models.CharField(blank=True, max_length=150)),
                ('access_token', models.CharField(blank=True, max_length=255)),
                ('qr_session_image', models.ImageField(blank=True, null=True, upload_to='whatsapp/session_qr/', validators=[config.validators.validate_image_file])),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mobile_number', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('response', models.TextField(blank=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_logs', to='bookings.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
