# Generated by Django 5.2.14 on 2026-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsetting',
            name='api_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='default_country_code',
            field=models.CharField(blank=True, default='91', max_length=5),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='service_name',
            field=models.CharField(default='Primary WhatsApp Scan', max_length=150),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='service_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='whatsappsetting',
            name='session_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
