from django.urls import path

from .views import (
    AreaBulkDeleteView,
    AreaCreateView,
    AreaDeleteView,
    AreaListView,
    AreaUpdateView,
    BuildingBulkDeleteView,
    BuildingCreateView,
    BuildingDeleteView,
    BuildingListView,
    BuildingUpdateView,
    CotBulkDeleteView,
    CotCreateView,
    CotDeleteView,
    CotListView,
    CotUpdateView,
    ExcelUploadView,
    FloorBulkDeleteView,
    FloorCreateView,
    FloorDeleteView,
    FloorListView,
    FloorUpdateView,
    RoomBulkDeleteView,
    RoomCreateView,
    RoomDeleteView,
    RoomListView,
    RoomUpdateView,
    SectionBulkDeleteView,
    SectionCreateView,
    SectionDeleteView,
    SectionListView,
    SectionUpdateView,
    SystemSettingView,
)


urlpatterns = [
    path("areas/", AreaListView.as_view(), name="panel_area_list"),
    path("areas/add/", AreaCreateView.as_view(), name="panel_area_create"),
    path("areas/<int:pk>/edit/", AreaUpdateView.as_view(), name="panel_area_update"),
    path("areas/<int:pk>/delete/", AreaDeleteView.as_view(), name="panel_area_delete"),
    path("areas/bulk-delete/", AreaBulkDeleteView.as_view(), name="panel_area_bulk_delete"),
    path("buildings/", BuildingListView.as_view(), name="panel_building_list"),
    path("buildings/add/", BuildingCreateView.as_view(), name="panel_building_create"),
    path("buildings/<int:pk>/edit/", BuildingUpdateView.as_view(), name="panel_building_update"),
    path("buildings/<int:pk>/delete/", BuildingDeleteView.as_view(), name="panel_building_delete"),
    path("buildings/bulk-delete/", BuildingBulkDeleteView.as_view(), name="panel_building_bulk_delete"),
    path("sections/", SectionListView.as_view(), name="panel_section_list"),
    path("sections/add/", SectionCreateView.as_view(), name="panel_section_create"),
    path("sections/<int:pk>/edit/", SectionUpdateView.as_view(), name="panel_section_update"),
    path("sections/<int:pk>/delete/", SectionDeleteView.as_view(), name="panel_section_delete"),
    path("sections/bulk-delete/", SectionBulkDeleteView.as_view(), name="panel_section_bulk_delete"),
    path("floors/", FloorListView.as_view(), name="panel_floor_list"),
    path("floors/add/", FloorCreateView.as_view(), name="panel_floor_create"),
    path("floors/<int:pk>/edit/", FloorUpdateView.as_view(), name="panel_floor_update"),
    path("floors/<int:pk>/delete/", FloorDeleteView.as_view(), name="panel_floor_delete"),
    path("floors/bulk-delete/", FloorBulkDeleteView.as_view(), name="panel_floor_bulk_delete"),
    path("rooms/", RoomListView.as_view(), name="panel_room_list"),
    path("rooms/add/", RoomCreateView.as_view(), name="panel_room_create"),
    path("rooms/<int:pk>/edit/", RoomUpdateView.as_view(), name="panel_room_update"),
    path("rooms/<int:pk>/delete/", RoomDeleteView.as_view(), name="panel_room_delete"),
    path("rooms/bulk-delete/", RoomBulkDeleteView.as_view(), name="panel_room_bulk_delete"),
    path("cots/", CotListView.as_view(), name="panel_cot_list"),
    path("cots/add/", CotCreateView.as_view(), name="panel_cot_create"),
    path("cots/<int:pk>/edit/", CotUpdateView.as_view(), name="panel_cot_update"),
    path("cots/<int:pk>/delete/", CotDeleteView.as_view(), name="panel_cot_delete"),
    path("cots/bulk-delete/", CotBulkDeleteView.as_view(), name="panel_cot_bulk_delete"),
    path("excel-upload/", ExcelUploadView.as_view(), name="panel_excel_upload"),
    path("settings/", SystemSettingView.as_view(), name="panel_system_settings"),
]
