# Generated by Django 5.2.14 on 2026-06-02 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gateaccesslog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to='bookings.student'),
        ),
        migrations.AddField(
            model_name='studentaccess',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='student_access', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='studentaccess',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_records', to='bookings.student'),
        ),
        migrations.AddField(
            model_name='studentaccesshistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_access_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentaccesshistory',
            name='student_access',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='access_control.studentaccess'),
        ),
    ]
