# Generated by Django 5.2.14 on 2026-06-02 09:22

import config.validators
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hostel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=10, validators=[config.validators.validate_mobile_number])),
                ('whatsapp_number', models.CharField(max_length=10, validators=[config.validators.validate_whatsapp_number])),
                ('relative_contact_number', models.CharField(blank=True, max_length=10, validators=[config.validators.validate_mobile_number])),
                ('education', models.CharField(blank=True, max_length=200)),
                ('purpose_for_cot_booking', models.TextField()),
                ('address', models.TextField()),
                ('city_village', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('pincode', models.CharField(max_length=6, validators=[config.validators.validate_pincode])),
                ('student_photo', models.ImageField(blank=True, null=True, upload_to='students/photos/', validators=[config.validators.validate_image_file])),
                ('address_proof_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('driving_license', 'Driving License'), ('other', 'Other')], max_length=20)),
                ('address_proof_front', models.ImageField(upload_to='students/proofs/front/', validators=[config.validators.validate_image_file])),
                ('address_proof_back', models.ImageField(blank=True, null=True, upload_to='students/proofs/back/', validators=[config.validators.validate_image_file])),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking_from_date', models.DateField()),
                ('booking_to_date', models.DateField(blank=True, null=True)),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('security_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('booking_status', models.CharField(choices=[('pending_admin_confirmation', 'Pending Admin Confirmation'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('vacated', 'Vacated')], default='pending_admin_confirmation', max_length=30)),
                ('admin_remark', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bookings', to=settings.AUTH_USER_MODEL)),
                ('cot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='hostel.cot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='bookings.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyRentDue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bill_month', models.PositiveSmallIntegerField()),
                ('bill_year', models.PositiveSmallIntegerField()),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bill_type', models.CharField(choices=[('partial_first_month', 'Partial First Month'), ('regular_monthly', 'Regular Monthly'), ('manual', 'Manual')], max_length=25)),
                ('total_days_in_month', models.PositiveSmallIntegerField(default=0)),
                ('billable_days', models.PositiveSmallIntegerField(default=0)),
                ('due_date', models.DateField()),
                ('grace_period_end_date', models.DateField()),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('pending_verification', 'Pending Verification'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='unpaid', max_length=25)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('utr_transaction_id', models.CharField(blank=True, max_length=100)),
                ('payment_screenshot', models.ImageField(blank=True, null=True, upload_to='monthly_rent/screenshots/', validators=[config.validators.validate_image_file])),
                ('admin_remark', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_dues', to='bookings.booking')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_bills', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monthly_dues', to='bookings.student')),
            ],
            options={
                'ordering': ['-bill_year', '-bill_month', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('booking', 'bill_year', 'bill_month'), name='unique_bill_per_booking_month')],
            },
        ),
    ]
