# Generated by Django 5.2.14 on 2026-06-02 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name'], 'verbose_name': 'Guest', 'verbose_name_plural': 'Guests'},
        ),
        migrations.AddField(
            model_name='student',
            name='guest_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='city_village',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='student',
            name='purpose_for_cot_booking',
            field=models.TextField(blank=True, default=''),
        ),
    ]
